extends: github.com/stepro/mindaro/environments/azure-dev.yaml
variables:
  AZURE_RESOURCE_GROUP: bikesharing-dev
  AZURE_LOCATION: westus
  IMAGE_REGISTRY: stephpr.azurecr.io
  IMAGE_REGISTRY_USERNAME: stephpr
